//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NosAyudamos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NosAyudamos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current instance is read-only, so events cannot be produced..
        /// </summary>
        internal static string DomainObject_ReadOnly {
            get {
                return ResourceManager.GetString("DomainObject_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize empty data..
        /// </summary>
        internal static string PersonRepository_EmptyData {
            get {
                return ResourceManager.GetString("PersonRepository_EmptyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize empty event type..
        /// </summary>
        internal static string PersonRepository_EmptyEventType {
            get {
                return ResourceManager.GetString("PersonRepository_EmptyEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event type &apos;{0}&apos; is not valid..
        /// </summary>
        internal static string PersonRepository_InvalidEventType {
            get {
                return ResourceManager.GetString("PersonRepository_InvalidEventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person with ID &apos;{0}&apos; was not found..
        /// </summary>
        internal static string PersonRepository_NationalIdNotFound {
            get {
                return ResourceManager.GetString("PersonRepository_NationalIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciando.
        /// </summary>
        internal static string Startup_Starting {
            get {
                return ResourceManager.GetString("Startup_Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias {0} por tu mensaje. Actualmente estamos limitando la ayuda a personas que no tributan impuesto a las ganancias..
        /// </summary>
        internal static string UI_Donee_HasIncomeTax {
            get {
                return ResourceManager.GetString("UI_Donee_HasIncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias {0} por tu mensaje. Actualmente estamos limitando la ayuda a personas registradas en el régimen de Monotributo en la categoría A exclusivamente..
        /// </summary>
        internal static string UI_Donee_HighCategory {
            get {
                return ResourceManager.GetString("UI_Donee_HighCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias {0} por tu mensaje. Actualmente estamos limitando la ayuda a personas registradas en el régimen de Monotributo en la categoría A exclusivamente..
        /// </summary>
        internal static string UI_Donee_NotApplicable {
            get {
                return ResourceManager.GetString("UI_Donee_NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamento tener problemas para reconocer tu DNI. Ya avisé a los seres humanos que programaron esto para que me ayuden. Se van a contactar con vos a la brevedad. Perdón y gracias de nuevo por tu paciencia!.
        /// </summary>
        internal static string UI_Donee_RegistrationFailed {
            get {
                return ResourceManager.GetString("UI_Donee_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por tu mensaje! Lamentablemente, no pudimos verificar tu cuenta..
        /// </summary>
        internal static string UI_Donee_Rejected {
            get {
                return ResourceManager.GetString("UI_Donee_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recibimos tu mensaje, pero no pudimos reconocer tus datos en la imagen. Podrías enviarnos una nueva foto del DNI, quizás con mejor iluminación o más de cerca? Es importante que cuando tomes la foto, el DNI ocupe la totalidad de la pantalla de tu celular. Gracias por tu paciencia!.
        /// </summary>
        internal static string UI_Donee_ResendIdentifier1 {
            get {
                return ResourceManager.GetString("UI_Donee_ResendIdentifier1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sigo sin poder reconocer tus datos :(. Intentemos una última vez antes de involucrar a las personas de soporte técnico, que siempre aprecian que agotemos nuestras posibilidades primero. Buscá si es posible un lugar sin sombra y con luz natural (cuanta más, mejor!), y recordá que el DNI debería ocupar toda la pantalla de tu aplicación de cámara de fotos. Vamos que la tercera es la vencida!.
        /// </summary>
        internal static string UI_Donee_ResendIdentifier2 {
            get {
                return ResourceManager.GetString("UI_Donee_ResendIdentifier2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesitás ayuda? Por favor decinos cuánto necesitas..
        /// </summary>
        internal static string UI_Donee_SendAmount {
            get {
                return ResourceManager.GetString("UI_Donee_SendAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por tu mensaje! Por favor envianos una foto de tu DNI para registrarte para recibir ayuda..
        /// </summary>
        internal static string UI_Donee_SendIdentifier {
            get {
                return ResourceManager.GetString("UI_Donee_SendIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola {0}, bienvenid{1} a la comunidad de Nos Ayudamos! INSTRUCCIONES.
        /// </summary>
        internal static string UI_Donee_Welcome {
            get {
                return ResourceManager.GetString("UI_Donee_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por tu mensaje! Cuánto querés donar?.
        /// </summary>
        internal static string UI_Donor_SendAmount {
            get {
                return ResourceManager.GetString("UI_Donor_SendAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gracias por tu mensaje! Comentanos si necesitas ayuda o estás interesando en ayudar a otros..
        /// </summary>
        internal static string UI_UnknownIntent {
            get {
                return ResourceManager.GetString("UI_UnknownIntent", resourceCulture);
            }
        }
    }
}
